### ISSUE TITLE
Cannot craft EnderIO Conduit Switch

### ISSUE THREAD

**Issue by pyure** [JasonMcRay/InfiTech-Reloaded#10]
Requires "Redstone Conduit", which is crafted with three ore-dicted Red Alloy Ingots in a row according to NEI, but in practice they give Blue Power "Red Allow Wire" instead.

**Comment by JasonMcRay** [comment]
Fixed in IT:2 v3
(https://github.com/JasonMcRay/InfiTech-1.7/commit/5caaff1f6469223254518528e0f9505af15046ac)
