### ISSUE TITLE
Add IC2 Nuclear Fuel recipes to GT Canner

### ISSUE THREAD

**Issue by pyure** [JasonMcRay/InfiTech-Reloaded#11]
Currently the IC2 fuel canning recipes only work in the IC2 canner.  This is pointlessly annoying, they should be valid in the GT canner.

I'm not sure what the power consumption should be, but fairly low considering they operate in the ic2 canner just fine.

**Comment by pyure** [comment]
The recipes are
Fuel Rod (MOX) 4434
Fuel Rod (Uranium) 4437

Fuel Rod (Thorium) 6681 could be added as well for balance purposes.  Its currently a shaped recipe (Fuel Rod + Thorium = Thorium Fuel Rod).

**Comment by JasonMcRay** [comment]
Implemented in IT:2 v3
(https://github.com/JasonMcRay/InfiTech-1.7/commit/72a4f6c6b7955e760135465b72f45f88503c0ab6)
