### ISSUE TITLE
Iron Nuggets sometimes smelt to Steel instead of Wrought Iron

### ISSUE THREAD

**Issue by TedKnudsen** [JasonMcRay/InfiTech-Reloaded#5]
Problem may be due to Magic Bees Iron nuggets.  Usually these automatically transform into GT nuggets when they're in your inventory, but if MB iron nuggets stay MB and then feed into a furnace they'll convert to steel.

I believe I've also seen GT nuggets transform into MB nuggets when left alone in a chest (unconfirmed, possibly when loading a world)

**Comment by JasonMcRay** [comment]
Thanks for report. Fixed in v0.0.7

**Comment by TedKnudsen** [comment]
Jason does your fix also apply to RC nuggets by any chance?  I noticed on the weekend that they're affected too (not tested in v.0.0.7 yet)

**Comment by JasonMcRay** [comment]
It should affect all of the iron nuggets. Reason this was happening is I had disabled railcraft Blast Furnace in RC configs. Railcraft is that "smart" that it will try to find another way of making the steel. Re-enabling Blast Furnace and letting GregTech to disable it internaly (thanks to @Blood-Asp for this) fixed this long standing issue.

**Comment by TedKnudsen** [comment]
Fantastic! :)
