### ISSUE TITLE
Confusions and not working things in Blue Power mega issue thread :)

### ISSUE THREAD

**Issue by JasonMcRay** [JasonMcRay/InfiTech-Reloaded#6]
- [x] 1) Purple Alloy is getting unified into Endium
- [x] 2) There are wierd recipes in GT Alloy Smelter (like Endium block + ingot mod = 9x purple Alloy ingot)
- [x] 3) Infused Teslatite Dust is obtainable by macerating fire, or pulverizing Frosted Stone (ExU)
- [x] 4) Screwdriver handle is not craftable
- [x] 5) Can't get colored canvas bags
- [x] 6) Unable to craft any Lumars
- [x] 7) Unable to craft paint cans with diferent colors
- [x] 8) Unable to craft paint bruches with diferent colors
- [x] 9) Fine copper and iron wires arent craftable
- [x] 10) Restriction tubes (both) not craftable
- [x] 11) Silicon Wafer not craftable
- [x] 12) Infused Teslatite Dust not obtainable

**Comment by JasonMcRay** [comment]
And there seems to be a lot more confused recipes.
- Infused Teslatite Dust

**Comment by JasonMcRay** [comment]
All of above issues doesnt appear without GT

**Comment by pyure** [comment]
1) Confirmed, unifies into Endium
2) Cannot reproduce (and NEI doesn't work well with HEE, hard to see recipes)
Possibly related:
* with "GemBlocksForGreg"  mod: many of these blocks do alloy-smelter into 9 Endium ingots.
* so does a vanilla hopper alloy-smelts to 9 endium ingots *URGENT*
* so does Border Stone (Alternate) from extra utils.
* Many of these recipes also regular-furnace into endium ingots
3) Confirmed frosted stone.  Also smelts to endium ingots.
4) Could not reproduce.  Handle = stick + indigo dye.  Indigo dye derived from indigo flower.  Recipe works.
5) Could not reproduce.  White canvas bag plus dye creates colored canvas bag.
6) Could not reproduce.  2 Dyes + Redstone + Glowstone = Lumar.
7) Could not reproduce.  All recipes work fine.
8) Could not reproduce.  Paint cans work.   Paint brushes work.  Can + Brush = colored brush.
9) Could not reproduce.  Shaped recipe and Wiremill recipe works fine.
10) Could not reproduce.  Also, the first tube recipe gives an achievement, yay :)
11) Could not reproduce.  Boule works,  Saw works,  Boule + Saw = Wafer.  Warning: Saw is Microblocks version only.

**Comment by JasonMcRay** [comment]
@Pyure were you gtesting with GT5.07.07 or BloodAsps version?

**Comment by JasonMcRay** [comment]
Updated to GT5.08.09. Unification issues 1) and 2) solved.
Rest still happens.

**Comment by pyure** [comment]
Jason, I'm testing with blood asp's version since he's theoretically providing you the fixes afaik. 

Thanks for the HEE tip, I had no idea!

**Comment by JasonMcRay** [comment]
Problem has been found.... Seems like I was still using the broken extrautils.zs script where ALL shapeless recipes were gone... derp
