### ISSUE TITLE
Add Cake recipe

### ISSUE THREAD

**Issue by pyure** [JasonMcRay/InfiTech-Reloaded#7]
Cake is, surprisingly, an important recipe for PneumaticCraft.  Its also annoying as hell to make.

There are two existing recipes which use vanilla resources and Pams, I'm proposing a recipe which blends the two a bit to preserve sanity. 

Add to harvestcraft.zs.  Tested.

var cake = <<minecraft:cake>>;
var allMilk =  <<ore:listAllmilk>>;
var sugar = <<minecraft:sugar>>;
var allegg = <<ore:listAllegg>>;
var flourwheat =  <<ore:flourEqualswheat>>;

recipes.addShaped(cake, [
	[allMilk, allMilk, allMilk],
	[sugar, allegg, sugar],
	[flourwheat, flourwheat, flourwheat]]);

**Comment by pyure** [comment]
edited to escape-out the angle brackets, didn't realize github ate them.

**Comment by pyure** [comment]
wontadd?

I cannot submit issues if you don't explain.

**Comment by JasonMcRay** [comment]
Sorry, forgot to type that.

I dont see real reason to add this. I know cake is somewhat important in PC, but it was made with this in mind.
Also with this there is the issue of buckets not being returned if they are used in the crafting.
